services:
  - type: web
    name: my-tasks
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: uvicorn server:app --host=0.0.0.0 --port=10000
